### ISSUE TITLE
unicast_prefix_v4 deletes

### ISSUE THREAD

**Issue by brmcdoug** [sbezverk/gobmp#145]
when unicast_prefix_v4 entries are removed from routing table, there are no corresponding "del" messages on Kafka

**Comment by sbezverk** [comment]
@brmcdoug could you please enable --v=6 and then try to flap a single prefix, please add collected output to the issue.

**Comment by brmcdoug** [comment]
[unicasst_prefix_flap.txt](https://github.com/sbezverk/gobmp/files/5940580/unicasst_prefix_flap.txt)
