### ISSUE TITLE
peer delete message

### ISSUE THREAD

**Issue by brmcdoug** [sbezverk/gobmp#149]
After clearing or deleting an XR BGP session the BGP peer/node entry is not deleted from Arango and 'del' message is not seen on kafka.

gobmp log:

I0321 21:45:38.315876       1 common-header.go:25] BMP CommonHeader Raw: [ 0x03, 0x00, 0x00, 0x00, 0x46, 0x02 ]
I0321 21:45:38.315970       1 common-header.go:25] BMP CommonHeader Raw: [ 0x03, 0x00, 0x00, 0x00, 0x46, 0x02 ]
I0321 21:45:38.315993       1 per-peer-header.go:73] BMP Per Peer Header Raw: [ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xC6, 0x3E, 0x9A, 0x01, 0x00, 0x00, 0xFA, 0x20, 0x0A, 0x00, 0x00, 0x20, 0x60, 0x57, 0xBE, 0xC8, 0x00, 0x04, 0x78, 0x96, 0x01, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x15, 0x03, 0x06, 0x04 ]
I0321 21:45:38.316023       1 peer-down.go:19] BMP Peer Down Message Raw: [ 0x01, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x15, 0x03, 0x06, 0x04 ]
E0321 21:45:38.316059       1 peer.go:19] got invalid Payload type in bmp.Message &{Reason:1 Data:[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 21 3 6 4]}
I0321 21:45:47.898576       1 common-header.go:25] BMP CommonHeader Raw: [ 0x03, 0x00, 0x00, 0x00, 0x64, 0x01 ]
I0321 21:45:47.898616       1 common-header.go:25] BMP CommonHeader Raw: [ 0x03, 0x00, 0x00, 0x00, 0x4C, 0x01 ]
I0321 21:45:47.898662       1 common-header.go:25] BMP CommonHeader Raw: [ 0x03, 0x00, 0x00, 0x00, 0x4C, 0x01 ]
I0321 21:45:47.898687       1 per-peer-header.go:73] BMP Per Peer Header Raw: [ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xC6, 0x3E, 0x9A, 0x01, 0x00, 0x00, 0xFA, 0x20, 0x00, 0x00, 0x00, 0x00, 0x60, 0x57, 0xBE, 0xD1, 0x00, 0x0D, 0x77, 0xBE, 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x33, 0x00, 0x02, 0x00, 0x04, 0x00, 0x00, 0x03, 0x5B, 0x00, 0x04, 0x00, 0x04, 0x00, 0x00, 0x01, 0x55 ]
I0321 21:45:47.898707       1 stats-report.go:20] BMP Stats Report Message Raw: [ 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x33, 0x00, 0x02, 0x00, 0x04, 0x00, 0x00, 0x03, 0x5B, 0x00, 0x04, 0x00, 0x04, 0x00, 0x00, 0x01, 0x55 ]
I0321 21:45:47.898727       1 information-tlv.go:21] BMP Informational TLV Raw: [ 0x00, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x33, 0x00, 0x02, 0x00, 0x04, 0x00, 0x00, 0x03, 0x5B, 0x00, 0x04, 0x00, 0x04, 0x00, 0x00, 0x01, 0x55 ]
I0321 21:45:47.898748       1 common-header.go:25] BMP CommonHeader Raw: [ 0x03, 0x00, 0x00, 0x00, 0x64, 0x01 ]
I0321 21:45:47.898778       1 per-peer-header.go:73] BMP Per Peer Header Raw: [ 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0x01, 0x04, 0x20, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0xFA, 0x20, 0x0A, 0x00, 0x00, 0x20, 0x60, 0x57, 0xBE, 0xD1, 0x00, 0x0D, 0x77, 0x6B, 0x00, 0x00, 0x00, 0x05, 0x00, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x08, 0x00, 0x02, 0x00, 0x04, 0x00, 0x00, 0x00, 0x24, 0x00, 0x04, 0x00, 0x04, 0x00, 0x00, 0x00, 0x16, 0x00, 0x07, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x08, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03 ]
I0321 21:45:47.898807       1 stats-report.go:20] BMP Stats Report Message Raw: [ 0x00, 0x00, 0x00, 0x05, 0x00, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x08, 0x00, 0x02, 0x00, 0x04, 0x00, 0x00, 0x00, 0x24, 0x00, 0x04, 0x00, 0x04, 0x00, 0x00, 0x00, 0x16, 0x00, 0x07, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x08, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03 ]
I0321 21:45:47.898832       1 information-tlv.go:21] BMP Informational TLV Raw: [ 0x00, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x08, 0x00, 0x02, 0x00, 0x04, 0x00, 0x00, 0x00, 0x24, 0x00, 0x04, 0x00, 0x04, 0x00, 0x00, 0x00, 0x16, 0x00, 0x07, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x08, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03 ]
I0321 21:45:47.898848       1 common-header.go:25] BMP CommonHeader Raw: [ 0x03, 0x00, 0x00, 0x00, 0x54, 0x01 ]
I0321 21:45:47.898878       1 common-header.go:25] BMP CommonHeader Raw: [ 0x03, 0x00, 0x00, 0x00, 0x54, 0x01 ]
I0321 21:45:47.898902       1 per-peer-header.go:73] BMP Per Peer Header Raw: [ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x01, 0x01, 0x00, 0x00, 0x00, 0xFD, 0xE8, 0x0A, 0x00, 0x00, 0x00, 0x60, 0x57, 0xBE, 0xD1, 0x00, 0x0D, 0x77, 0xC2, 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x0E, 0x00, 0x07, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07, 0x00, 0x08, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07 ]
I0321 21:45:47.898919       1 stats-report.go:20] BMP Stats Report Message Raw: [ 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x0E, 0x00, 0x07, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07, 0x00, 0x08, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07 ]
I0321 21:45:47.898941       1 information-tlv.go:21] BMP Informational TLV Raw: [ 0x00, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x0E, 0x00, 0x07, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07, 0x00, 0x08, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07 ]

**Comment by sbezverk** [comment]
@brmcdoug you are right, this logic has not been yet implemented. I believe, gobmp sends `peer down` message, but it will be responsibility of `topology` to react and perform a cleanup.

**Comment by brmcdoug** [comment]
I wasn't seeing any peer 'delete' or peer down messages on Kafka.  Does the gobmp log above have peer down/delete?

> @brmcdoug you are right, this logic has not been yet implemented. I believe, gobmp sends `peer down` message, but it will be responsibility of `topology` to react and perform a cleanup.
