### ISSUE TITLE
SRv6 locator flag

### ISSUE THREAD

**Issue by mirlos-pt** [sbezverk/gobmp#160]
There is a single flag for an LSPrefix srv6_locator entry defined in RFC at this time. It would be more consistent if the d_flag were parsed, and the name of the attribute being "flags" rather than "flag".

**Comment by sbezverk** [comment]
@mirlos-pt providing a link to RFC, would be very useful.

**Comment by mirlos-pt** [comment]
The RFC is https://tools.ietf.org/html/draft-ietf-idr-bgpls-srv6-ext-07#section-5.1.
