### ISSUE TITLE
adjacency-sid tlv should have "sid" instead of "prefix_sid"

### ISSUE THREAD

**Issue by brmcdoug** [sbezverk/gobmp#171]
On the ACP call today the team was looking at ls_link data and Peter noted that in adjacency sid tlv "prefix_sid" field should be renamed as "sid"

https://github.com/sbezverk/gobmp/blob/a04bca0ad1d03b5e37703298f29d3117c7f33fbb/pkg/sr/sr-adjacencysid.go#L33

Ketan also asks that we change SRv6 EndXSID sub_tlv_value from byte to uint32
https://github.com/sbezverk/gobmp/blob/a04bca0ad1d03b5e37703298f29d3117c7f33fbb/pkg/srv6/srv6-endxsidtlv.go#L45

it is not an urgent issue

**Comment by sbezverk** [comment]
@brmcdoug  No problem to fix json tag, but with regards to the second ask, it is not clear what exactly he wants. There is no `byte` in SubTLVs, SubTLVs is a slice of interfaces to cover all possible SRv6 SubTLVs. I would need an example how it should look what was asked.

**Comment by brmcdoug** [comment]
> @brmcdoug No problem to fix json tag, but with regards to the second ask, it is not clear what exactly he wants. There is no `byte` in SubTLVs, SubTLVs is a slice of interfaces to cover all possible SRv6 SubTLVs. I would need an example how it should look what was asked.

Ok, I'm not worried about the SubTLV item.  If Ketan brings it up again we can look into it in more detail.  thanks
