### ISSUE TITLE
Update the timestamp format to include year as well as using ISO format

### ISSUE THREAD

**Issue by lordofire** [sbezverk/gobmp#185]
In the current implementation of the streamed out message, the timestamp field is illustrated as `"timestamp":"Dec 20 06:17:33.000036"` It would be great to reformat this to include year into the message, and use iso format for the date representation like `'2021-12-20 06:17:33.000036'`. Thanks for your support in advance!

**Comment by sbezverk** [comment]
@lordofire  thank you for your suggestion. Would this format works for you? `2006-01-02T15:04:05.999999999Z07:00`
I would prefer to stay with time formats available in the standard golang time package.

**Comment by lordofire** [comment]
Yeah, this looks good to me, thanks!

**Comment by lordofire** [comment]
It would be great if you could publish a new version, like v1.0.1, to include the fixes we talked about before including this one. Thanks.
