### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by gitthehit** [sbezverk/gobmp#224]
Git clone with the latest code and build it, exit with an error.
```
go: finding github.com/nats-io/nats.go v1.25.0
go: finding github.com/nats-io/nkeys v0.4.4
go: finding golang.org/x/sys v0.7.0
go: finding github.com/nats-io/nuid v1.0.1
build command-line-arguments: cannot load crypto/ecdh: malformed module path "crypto/ecdh": missing dot in first path element
make[1]: *** [Makefile:2: compile-gobmp] Error 1
make[1]: Leaving directory '/home/ubuntu/Desktop/gobmp-master/cmd/gobmp'
make: *** [Makefile:16: gobmp] Error 2
```

**Comment by sbezverk** [comment]
Hello,

I just pulled the latest master and build gobmp, all looks good, please see below:

```
git log 
commit 5d9bcff6d66fa7450a91baf51eac0d9f512ee6f7 (HEAD -> master, origin/master, origin/HEAD)
Merge: 29b5fa2 8d0b531
Author: Serguei Bezverkhi <sbezverk@cisco.com>
Date:   Fri May 12 08:59:08 2023 +0200

    Merge pull request #219 from jarrodb/nats
    
    Thank you!
```

```
make gobmp
mkdir -p bin
/Library/Developer/CommandLineTools/usr/bin/make -C ./cmd/gobmp compile-gobmp
CGO_ENABLED=0 GOOS=linux GO111MODULE=on go build -a -ldflags '-extldflags "-static"' -o ../../bin/gobmp ./gobmp.go
go: downloading github.com/nats-io/nats.go v1.25.0
go: downloading github.com/klauspost/compress v1.16.4
go: downloading golang.org/x/net v0.9.0
go: downloading golang.org/x/crypto v0.8.0
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/nats-io/nkeys v0.4.4
go: downloading golang.org/x/sys v0.7.0
```
I would suggest to clean up your go cache and try again.

**Comment by gitthehit** [comment]
I am not using git. I just download the code within the zip.

Is there any packages needed to be installed? I'm not very familiar with how to use go to compile programs. I installed golang and make with apt.

**Comment by sbezverk** [comment]
You need to setup your golang environment properly in order to build the code from the source. There are multiple sources on the internet with guidelines how to do it. As alternative, I suggest to use already built a docker container.
`docker.io/sbezverk/gobmp:latest`

**Comment by gitthehit** [comment]
I can compile the code in release using the default environment, that is, the version is v1.0.2. But in the same environment, the latest code cannot be compiled.
