### ISSUE TITLE
[question] Why is this empty message parsed out?

### ISSUE THREAD

**Issue by gitthehit** [sbezverk/gobmp#229]
I am using the latest gobmp image, and I found that when bgp withdraws the message, the bottom line of information in the picture will appear. Is this normal behavior and is it possible to turn off the display of this information?
![3](https://github.com/sbezverk/gobmp/assets/49119921/ef916481-92da-4a3b-86ef-563806c96975)

**Comment by sbezverk** [comment]
It is EoR message sent by the router for each address family  to indicate that it has completed initial send of routes. See RFC for more detail. This message can be easily identified by `is_eor` set to true.

**Comment by gitthehit** [comment]
Ok I got it, thanks for your help and answers.
