### ISSUE TITLE
Does goBMP support sending parsed BMP data to another process instead of Kafka via TCP Socket? This can greatly simplify network deployment costs.

### ISSUE THREAD

**Issue by wangchong2023** [sbezverk/gobmp#234]
Does goBMP support sending parsed BMP data to another process instead of Kafka via TCP Socket? This can greatly simplify network deployment costs.

**Comment by sbezverk** [comment]
Hello, no it does not support it, but you are welcome to propose a PR with such support.

**Comment by wangchong2023** [comment]
> @wangchong2023 the reason I am not jumping on implementing it is because it is very opinionated deployment model, it will require designing a sort of simple protocol to send data over the socket. Since it is not standard, there is a good chance that other people will not be happy with designed protocol and would want to change it. For now I prefer to stick with "standard" and commonly used models, like kafka, or nats etc...

OK.Thanks for your help.
