### ISSUE TITLE
Wrong format for unidirectional link loss

### ISSUE THREAD

**Issue by severindellsperger** [sbezverk/gobmp#239]
In your code, you get the unidirectional loss as packet percentage between two directly connected IGP link-state neighbors: https://github.com/sbezverk/gobmp/blob/72822d6fd6b95592a5e5faefaf8e2549c7260119/pkg/bgpls/bgpls-nlri.go#L658-L667
In your case, you return the loss as an unsigned integer. However, according to [RFC8570](https://datatracker.ietf.org/doc/html/rfc8570#section-4.4), this should be encoded as a float to support the packet loss percentage, shouldn't it?

Can someone please confirm so that I can create a PR.

**Comment by sbezverk** [comment]
When you get the value in uint32, you just need to process it in your application as described in rfc. No need to change gobmp code.

**Comment by severindellsperger** [comment]
Alright, thanks.
