### ISSUE TITLE
crash in handling bgp live stream

### ISSUE THREAD

**Issue by SergeKrier** [sbezverk/gobmp#42]
I0421 05:07:35.347038    4124 route-monitor.go:26] BMP Route Monitor Message Raw: ffffffffffffffffffffffffffffffff0096020000007b400101005002001e02070003000d0000223600000ce700000cf800000b620000e45500009c814003045bce3467c008300b62019a0b6205810b6209630b620d480ce703ee0ce703fd0ce70c050cf804100cf807da0cf8233c2236006e2236012cc020180003000d00000003000000050003000d0000000400000003189ad144
Withdrawn Routes Length: 0
Total Path Attribute Length: 28
Attribute Type: 1 (ORIGIN)
   Origin: [0]
Attribute Type: 2 (AS_PATH)
   AS PATH: [ 0x02, 0x06, 0x73, 0xfb, 0x32, 0xe6, 0x93, 0x1e, 0x91, 0x54, 0xdd, 0x78, 0xdd, 0x78 ]
Attribute Type: 3
[ 0x5b, 0xce, 0x34, 0x09 ]
NLRI:

I0421 05:07:35.347046    4124 bgp-update.go:358] BGPUpdate Raw: 0000007b400101005002001e02070003000d0000223600000ce700000cf800000b620000e45500009c814003045bce3467c008300b62019a0b6205810b6209630b620d480ce703ee0ce703fd0ce70c050cf804100cf807da0cf8233c2236006e2236012cc020180003000d00000003000000050003000d0000000400000003189ad144
I0421 05:07:35.347142    4124 bgp-path-attribute.go:66] BGPPathAttributes Raw: [ 0x40, 0x01, 0x01, 0x00, 0x50, 0x02, 0x00, 0x1e, 0x02, 0x07, 0x00, 0x03, 0x00, 0x0d, 0x00, 0x00, 0x22, 0x36, 0x00, 0x00, 0x0c, 0xe7, 0x00, 0x00, 0x0c, 0xf8, 0x00, 0x00, 0x0b, 0x62, 0x00, 0x00, 0xe4, 0x55, 0x00, 0x00, 0x9c, 0x81, 0x40, 0x03, 0x04, 0x5b, 0xce, 0x34, 0x67, 0xc0, 0x08, 0x30, 0x0b, 0x62, 0x01, 0x9a, 0x0b, 0x62, 0x05, 0x81, 0x0b, 0x62, 0x09, 0x63, 0x0b, 0x62, 0x0d, 0x48, 0x0c, 0xe7, 0x03, 0xee, 0x0c, 0xe7, 0x03, 0xfd, 0x0c, 0xe7, 0x0c, 0x05, 0x0c, 0xf8, 0x04, 0x10, 0x0c, 0xf8, 0x07, 0xda, 0x0c, 0xf8, 0x23, 0x3c, 0x22, 0x36, 0x00, 0x6e, 0x22, 0x36, 0x01, 0x2c, 0xc0, 0x20, 0x18, 0x00, 0x03, 0x00, 0x0d, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x05, 0x00, 0x03, 0x00, 0x0d, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x03 ]
I0421 05:07:35.347157    4124 route.go:31] Routes Raw: [ 0x18, 0x9a, 0xd1, 0x44 ]
panic: runtime error: slice bounds out of range [:26] with capacity 25

goroutine 19972 [running]:
github.com/sbezverk/gobmp/pkg/bgp.(*Update).GetAttrASPath(0xc0000d37a0, 0xc000534701, 0x0, 0x0, 0x1)
	/home/sekrier/apr21/gobmp/pkg/bgp/bgp-update.go:105 +0x39a
github.com/sbezverk/gobmp/pkg/message.(*producer).nlri(0xc00001e0c0, 0x0, 0xc0000d3740, 0xc0000d37a0, 0x1500, 0x1, 0x0, 0x0, 0xc0003bbba0)
	/home/sekrier/apr21/gobmp/pkg/message/base-nlri.go:43 +0x8e6
github.com/sbezverk/gobmp/pkg/message.(*producer).produceRouteMonitorMessage(0xc00001e0c0, 0xc0000d3740, 0x805340, 0xc000206070)
	/home/sekrier/apr21/gobmp/pkg/message/route-monitor.go:64 +0xf1
github.com/sbezverk/gobmp/pkg/message.(*producer).producingWorker(0xc00001e0c0, 0xc0000d3740, 0x805340, 0xc000206070)
	/home/sekrier/apr21/gobmp/pkg/message/producer.go:41 +0x15c
created by github.com/sbezverk/gobmp/pkg/message.(*producer).Producer
	/home/sekrier/apr21/gobmp/pkg/message/producer.go:26 +0x74

**Comment by sbezverk** [comment]
@SergeKrier Is it the right as path:
```
29691, 13030, 37662, 37204, 56696, 56696
```
The issue here is because peer advertises AS4Path capability, but sending  2 bytes ASes in ASPath. In the test bed, we saw BGP speaker with AS4 Capability always sending 4 bytes ASes in AS Path. Need a reliable way to distinguish the AS Path type.
