### ISSUE TITLE
SRv6 LS_Link messages for End.X SIDs

### ISSUE THREAD

**Issue by brmcdoug** [sbezverk/gobmp#86]
Router has these SIDs:

RP/0/RP0/CPU0:R03#sho segment-routing srv6 sid all
Tue Aug 11 19:51:49.624 PDT

*** Locator: 'MAIN' *** 

SID                         Behavior     Context                           Owner               State  RW
--------------------------  -----------  ------------------------------    ------------------  -----  --
2001:1:1:f003:1::           End (PSP)    'default':1                       sidmgr              InUse  Y 
2001:1:1:f003:11::          End.OP       'default'                         sidmgr              InUse  Y 
2001:1:1:f003:40::          End.X (PSP)  [Gi0/0/0/1, Link-Local]           isis-100            InUse  Y 
2001:1:1:f003:41::          End.X (PSP)  [Gi0/0/0/0, Link-Local]           isis-100            InUse  Y 
2001:1:1:f003:42::          End.X (PSP)  [Gi0/0/0/2, Link-Local]           isis-100            InUse  Y 

The End (PSP) and End.OP SIDs come thru in ls_srv6_sid message. However, I believe the End.X ones come in ls_link messages:

https://tools.ietf.org/html/draft-ietf-idr-bgpls-srv6-ext-03#section-4

With GoBMP on log level 6 I see these entries the last one being an End.X SID TLV: 

I0812 03:48:20.803082       1 ls-nlri71.go:83] LSNLRI71 Raw: [ 0x00, 0x02, 0x00, 0x73, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x1a, 0x02, 0x00, 0x00, 0x04, 0x00, 0x01, 0x86, 0xa0, 0x02, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x1a, 0x02, 0x00, 0x00, 0x04, 0x00, 0x01, 0x86, 0xa0, 0x02, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x01, 0x05, 0x00, 0x10, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x01, 0x06, 0x00, 0x10, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x23, 0x01, 0x07, 0x00, 0x02, 0x00, 0x02 ] 
I0812 03:48:20.803141       1 link-nlri.go:123] LinkNLRI Raw: [ 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x1a, 0x02, 0x00, 0x00, 0x04, 0x00, 0x01, 0x86, 0xa0, 0x02, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x1a, 0x02, 0x00, 0x00, 0x04, 0x00, 0x01, 0x86, 0xa0, 0x02, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x01, 0x05, 0x00, 0x10, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x01, 0x06, 0x00, 0x10, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x23, 0x01, 0x07, 0x00, 0x02, 0x00, 0x02 ]
I0812 03:48:20.803161       1 node-descriptor.go:82] NodeDescriptor Raw: [ 0x01, 0x00, 0x00, 0x1a, 0x02, 0x00, 0x00, 0x04, 0x00, 0x01, 0x86, 0xa0, 0x02, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x00, 0x06, 0x00, 0x00 ]
I0812 03:48:20.803183       1 node-descriptor.go:82] NodeDescriptor Raw: [ 0x01, 0x01, 0x00, 0x1a, 0x02, 0x00, 0x00, 0x04, 0x00, 0x01, 0x86, 0xa0, 0x02, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x00, 0x06, 0x00, 0x00 ]
I0812 03:48:20.803209       1 link-descriptor.go:66] LinkDescriptor Raw: [ 0x01, 0x05, 0x00, 0x10, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x01, 0x06, 0x00, 0x10, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x23, 0x01, 0x07, 0x00, 0x02, 0x00, 0x02 ]
I0812 03:48:20.803262       1 bgpls-nlri.go:565] BGPLSNLRI Raw: [ 0x01, 0x02, 0x00, 0x08, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x07, 0x04, 0x06, 0x00, 0x04, 0x0a, 0x00, 0x00, 0x03, 0x04, 0x47, 0x00, 0x03, 0x00, 0x00, 0x01, 0x04, 0x52, 0x00, 0x1e, 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x20, 0x01, 0x00, 0x01, 0x00, 0x01, 0xf0, 0x00, 0x00, 0x43, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0xe4, 0x00, 0x04, 0x28, 0x18, 0x10, 0x00 ]
I0812 03:48:20.803296       1 bgpls-tlv.go:22] BGPLSTLV Raw: [ 0x01, 0x02, 0x00, 0x08, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x00, 0x00, 0x07, 0x04, 0x06, 0x00, 0x04, 0x0a, 0x00, 0x00, 0x03, 0x04, 0x47, 0x00, 0x03, 0x00, 0x00, 0x01, 0x04, 0x52, 0x00, 0x1e, 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x20, 0x01, 0x00, 0x01, 0x00, 0x01, 0xf0, 0x00, 0x00, 0x43, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0xe4, 0x00, 0x04, 0x28, 0x18, 0x10, 0x00 ]
I0812 03:48:20.803320       1 srv6-endxsidtlv.go:33] SRv6 End.X SID TLV Raw: [ 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x20, 0x01, 0x00, 0x01, 0x00, 0x01, 0xf0, 0x00, 0x00, 0x43, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0xe4, 0x00, 0x04, 0x28, 0x18, 0x10, 0x00 ]

**Comment by sbezverk** [comment]
This message comes as NLRI 71

`I0812 03:48:20.803082 1 ls-nlri71.go:83] LSNLRI71`

Then it is classified as  Link NLRI

`I0812 03:48:20.803141 1 link-nlri.go:123] LinkNLRI`

As per the RFC, link NLRI message has 2 Local Node Descriptor, Remote Node Descriptor  and Link Descriptor 

`I0812 03:48:20.803161 1 node-descriptor.go:82] NodeDescriptor`
`I0812 03:48:20.803183 1 node-descriptor.go:82] NodeDescriptor`
`I0812 03:48:20.803209 1 link-descriptor.go:66] LinkDescriptor`

Link descriptor carries BGP-LS TLVs 

`I0812 03:48:20.803296 1 bgpls-tlv.go:22] BGPLSTLV`

One of BGP-LS TLV is SRv6 End.X SID TLV
`I0812 03:48:20.803320 1 srv6-endxsidtlv.go:33] SRv6 End.X SID TLV`

Please let me know where you see inconsistency with RFC.

**Comment by sbezverk** [comment]
Closing as no new evidence of the inconsistency were provided.
